### PR TITLE
Social share

### PR DESCRIPTION
**Pull request by andela-bebowe**

### CODE REVIEW

**Comment by andela-ooranagwa** [comment]
I could eliminate the 3 files `_latest, popular, featured` by `rendering a common template` from the controller itself. I don't think there is anymore need for a partial.

**Comment by andela-iokonkwo** [comment]
What about the partial for the search event page?
Don't you think it will make sense for 4 to share a common partial.
In fact, the partial can be used anywhere an event card is needed.
The common template for the above 3 can use the partial. `<%= render @events %>`. The common template will contain other code like the `unless.. else..end` block, while the partial will be rendered in the `unless` section.

**Comment by andela-ooranagwa** [comment]
Hmmm. I overlooked the `search page`.

**Comment by andela-ooranagwa** [comment]
But I could still render the template there also. Using a partial might still find the controller wanting to render the default view for `featured` and `popular`. A template on the hand substitutes for those views.

**Comment by andela-iokonkwo** [comment]
I agree, we are going to use a `common template` for featured/popular/latest. But that common template will still use the partial. Refer back to my previous comment to better understand what I meant.

**Comment by andela-ooranagwa** [comment]
About the search page, do you think adding the `else` block will be nice? I think it will enable displaying better feedback when a search query returns nothing. In which case we need render the whole template.

**Comment by andela-iokonkwo** [comment]
That's true. That feedback is important. 
Yea, adding the `else` block will be nice.

**Comment by andela-ooranagwa** [comment]
I'm looking at `drying up` the code in `welcome/index.html.erb`. The `div`s there are replicated unnecessarily.

**Comment by andela-iokonkwo** [comment]
Please do. Also the implementation of latest/featured/popular is not clean at all. We need to modify how the ajax call is been made. Let's talk on hangout.

**Comment by andela-iokonkwo** [comment]
We are going to use `remote: true` to make an ajax call that will update our event each time we click on the latest/popular/featured event tab.

**Comment by andela-iokonkwo** [comment]
Just like how it is done on the search event page.

**Pull request closed without merging**
