### PR TITLE
Ft add to calendar 114780531

### PR DESCRIPTION
**Pull request by andela-fsenjobi**
This merge will include the add to calendar and add to google calendar feature

### CODE REVIEW

**Comment by andela-iokonkwo** [comment]
@andela-fsenjobi Why are there still HoundCI issues on this PR. Also it seems you have not squashed the commits.

**Comment by andela-fsenjobi** [comment]
@andela-iokonkwo The issues are as a result of the feature. The commits have now been squashed and HoundCI issues resolved except 2. The unresolved ones can be ignored as we do not want to escape anything within the string.

**Comment by andela-iokonkwo** [comment]
@andela-fsenjobi After squashing, it makes sense to delete the remote branch before pushing. This is because the remote branch will contain previous commit that has been squashed if it was not deleted. Just like in this case. I will be closing this PR and deleting the branch now. Once done, push again to create a new remote branch.

**Comment by andela-fsenjobi** [comment]
@andela-iokonkwo :+1: noted.

**Comment by andela-iokonkwo** [comment]
@andela-fsenjobi I am curious as to why you reopened this closed PR?

**Comment by andela-fsenjobi** [comment]
@andela-iokonkwo All the requested changes have been done and I thought using an already existing PR from the same branch will do

**Comment by andela-iokonkwo** [comment]
Let's pair on this during our one-on-one session today.

**Comment by andela-fsenjobi** [comment]
@andela-iokonkwo That would be great

**Pull request closed without merging**
