### PR TITLE
Modified all files to follow JSHINT style guide

### PR DESCRIPTION
**Pull request by andela-sdamian**
Why?
This was done in other to follow style guide suggested by JSHINT

### CODE REVIEW

**Comment by andela-iokonkwo** [comment]
Awesome job guys. This is good. :+1: 
Just a little issue with the test. I believe it has to do with the commented out `puma` :gem:  in the Gemfile.
Always remember to uncomment it before you push.

**Comment by andela-fsenjobi** [comment]
@andela-iokonkwo is there a more permanent solution to PUMA? The need to regularly comment and uncomment seems to be drawing more attention by the day

**Comment by andela-iokonkwo** [comment]
@andela-fsenjobi Can you tell me the reasons why we have to comment and uncomment?

**Comment by andela-fsenjobi** [comment]
Puma is a web server. While I am not so sure why we have to comment and uncomment it, I believe it creates a live environment, a local server. So, where such service is available, there is no need to run puma.

**Comment by andela-iokonkwo** [comment]
@andela-fsenjobi The reason we puma was commented out initially was because it doesn't bind to `lvh.me` automatically. `lvh.me` is needed when working with subdomains since we can't visit subdomains via `localhost` when developing. The solution is to bind rails server to `lvh.me` with `rails server -b lvh.me`

**Pull request merged**
